version: 2

models:
  - name: dim_airlines
    description: "Dimension table containing unique airlines"
    columns:
      - name: airline_code
        description: "Two-letter IATA airline code (Primary Key)"
        tests:
          - unique
          - not_null
      
      - name: airline_name
        description: "Full commercial name of the airline"
        tests:
          - not_null

  - name: dim_routes
    description: "Dimension table defining unique flight paths"
    columns:
      - name: route_key
        description: "Unique key of Origin + Destination"
        tests:
          - unique
          - not_null

      - name: origin_airport
        description: "IATA Airport Code for Origin"
        tests:
          - not_null

      - name: dest_airport
        description: "IATA Airport Code for Destination"
        tests:
          - not_null

      - name: distance_miles
        description: "Average distance between airports"
        tests:
          - not_null

  - name: dim_date
    description: "Date dimension table"
    columns:
      - name: date_key
        description: "Date key in YYYYMMDD format"
        tests:
          - unique
          - not_null

  - name: fact_flight_prices
    description: "Fact table for flight prices"
    columns:
      - name: route_key
        tests:
          - not_null

      - name: date_key
        tests:
          - not_null

      - name: airline_key
        tests:
          - not_null

      - name: total_fare
        tests:
          - not_null

      - name: days_until_flight
        tests:
          - not_null

      - name: seats_remaining
        tests:
          - not_null

      - name: is_basic_economy
        tests:
          - not_null

      - name: is_non_stop
        tests:
          - not_null

  - name: ml_flight_pricing
    description: "Denormalized table for ML training"
    columns:
      - name: total_fare
        tests:
          - not_null

      - name: days_until_flight
        tests:
          - not_null

      - name: origin_city
        tests:
          - not_null

      - name: is_holiday
        tests:
          - not_null
          - accepted_values:
              values: [0, 1]
